module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: {
    standard: [
      /^home-/,
      /^hero-/,
      /^role-/,
      /^system-/,
      /^map-/,
      /^node-/,
      /^line-/,
      /^split-/,
      /^section-/,
      /^work-/,
      /^reading-/,
      /^mini-/,
      /^closing-/,
      /^case-/,
      /^book-/,
      /^quiet-/,
      /^udes-/,
      /^text-link$/,
    ],
    deep: [/^pagination$/, /^udes-/],
  },
};
