import { chromium } from "playwright";
import assert from "node:assert/strict";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto(process.env.BLOCH_QA_URL || "http://127.0.0.1:5189/");
await page.waitForFunction(() => window.__BLOCH_API__);
await page.getByRole("button", { name: "Explore freely", exact: true }).click();
const state = () => page.evaluate(() => window.__BLOCH_API__.getState()),
  click = (n) => page.getByRole("button", { name: n, exact: true }).click(),
  done = () => page.waitForFunction(() => !window.__BLOCH_API__.getState().animating),
  vec = (a, b) => a.forEach((x, i) => assert.ok(Math.abs(x - b[i]) < 1e-7));
for (const g of ["H", "Z", "H"]) await click(g);
vec((await state()).vector, [0, 0, 1]);
assert.deepEqual((await state()).sequence.queue, ["H", "Z", "H"]);
await page.screenshot({ path: "verification/sequence-queued.png" });
await click("Run");
await page.waitForTimeout(350);
await page.evaluate(() => window.__BLOCH_API__.act("remove:0"));
assert.deepEqual((await state()).sequence.queue, ["H", "Z", "H"]);
await click("Pause");
const frozen = (await state()).vector;
await page.waitForTimeout(350);
vec((await state()).vector, frozen);
await click("Step");
await done();
vec((await state()).vector, [1, 0, 0]);
assert.equal((await state()).sequence.cursor, 1);
assert.equal((await state()).sequence.status, "paused");
await page.screenshot({ path: "verification/sequence-step.png" });
await click("Resume");
await page.waitForTimeout(350);
assert.equal(await page.locator("#sequence-list button.current").count(), 1);
assert.match(await page.locator("#sequence-list button.current").getAttribute("aria-label"), /gate 2 Z/);
await page.screenshot({ path: "verification/sequence-running.png" });
await page.waitForFunction(() => window.__BLOCH_API__.getState().sequence.status === "complete");
vec((await state()).vector, [0, 0, -1]);
assert.deepEqual((await state()).history, ["H", "Z", "H"]);
await click("Measure 100 fresh qubits");
await page.waitForFunction(() => !window.__BLOCH_API__.getState().measuring);
assert.deepEqual((await state()).counts, [0, 100]);
await page.screenshot({ path: "verification/sequence-result.png" });
await click("Run");
await page.waitForFunction(() => window.__BLOCH_API__.getState().sequence.status === "complete");
vec((await state()).vector, [0, 0, -1]);
await click("Replay");
await page.waitForTimeout(250);
await click("Replay");
await page.waitForFunction(() => window.__BLOCH_API__.getState().sequence.status === "complete");
vec((await state()).vector, [0, 0, -1]);
await click("Remove gate 2 Z");
assert.deepEqual((await state()).sequence.queue, ["H", "H"]);
vec((await state()).vector, [0, 0, 1]);
await click("Run");
await page.waitForTimeout(150);
await click("Clear");
assert.deepEqual((await state()).sequence.queue, []);
await page.waitForTimeout(1200);
vec((await state()).vector, [0, 0, 1]);
assert.deepEqual((await state()).history, []);
for (const g of ["X", "X"]) await click(g);
await click("Run");
await click("Reset to |0⟩");
await page.getByRole("button", { name: "Explore freely", exact: true }).click();
await page.waitForTimeout(1250);
assert.deepEqual((await state()).sequence.queue, []);
vec((await state()).vector, [0, 0, 1]);
await page.evaluate(() => window.__BLOCH_API__.previewVRLayout());
for (const g of ["H", "Z", "H"]) await page.evaluate((g) => window.__BLOCH_API__.simulateControllerSelect("gate:" + g), g);
await page.evaluate(() => window.__BLOCH_API__.simulateControllerSelect("sequence-run"));
await page.waitForFunction(() => window.__BLOCH_API__.getState().sequence.status === "complete");
vec((await state()).vector, [0, 0, -1]);
await page.screenshot({ path: "verification/sequence-vr-layout.png" });
await page.evaluate(() => window.__BLOCH_API__.simulateControllerSelect("remove:1"));
assert.deepEqual((await state()).sequence.queue, ["H", "H"]);
await page.evaluate(() => window.__BLOCH_API__.simulateControllerSelect("sequence-clear"));
assert.deepEqual((await state()).sequence.queue, []);
await page.setViewportSize({ width: 390, height: 844 });
await page.reload();
await page.waitForFunction(() => window.__BLOCH_API__);
await page.getByRole("button", { name: "Explore freely", exact: true }).click();
for (const g of ["H", "S", "T", "X", "Y", "Z", "H", "T"]) await click(g);
assert.equal((await state()).sequence.queue.length, 8);
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
await page.screenshot({ path: "verification/sequence-phone.png", fullPage: true });
assert.deepEqual(errors, []);
await browser.close();
console.log("PASS sequence queue/order, pause/step, replay, busy editing, clear/reset, controller rays and phone");
