name: Axe accessibility testing

on:
  pull_request:
    branches:
      - main
    paths:
      - "assets/**"
      - "_includes/**"
      - "_layouts/**"
      - "_pages/**"
      - "_posts/**"
      - "_projects/**"
      - "_sass/**"
      - "**.html"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
  workflow_dispatch:
    inputs:
      url:
        description: "URL to be checked (e.g.: blog/)"
        required: false

env:
  URL: ""

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Prepare build config
        run: |
          ruby -ryaml -e 'config = YAML.load_file("_config.yml"); config["giscus"] ||= {}; config["giscus"]["repo"] = ENV.fetch("GITHUB_REPOSITORY"); config["baseurl"] = ""; File.write("_config.yml", config.to_yaml)'

      - name: Install and build
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          python -m pip install --upgrade pip
          python -m pip install --upgrade nbconvert
          export JEKYLL_ENV=production
          bundle exec jekyll build --trace

      - name: Purge unused CSS
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js

      - name: Get Chromium version
        run: |
          CHROMIUM_VERSION=$(wget -qO- https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE | cut -d. -f1)
          echo "Chromium version: $CHROMIUM_VERSION"
          echo "CHROMIUM_VERSION=$CHROMIUM_VERSION" >> $GITHUB_ENV

      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ env.CHROMIUM_VERSION }}

      - name: Install chromedriver
        run: npm install -g chromedriver@$CHROMIUM_VERSION

      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          npm install -g http-server
          http-server _site/ &
          axe --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver http://localhost:8080/${{ github.event.inputs.url || env.URL }} --load-delay=1500 --exit
